services:
  laravel:
    container_name: toledanonews-laravel
    build: .
    volumes:
      - ./laravel:/var/www/html
    ports:
      - 9000:80

  mysql_db:
    container_name: toledanonews-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toledanonews

  phpmyadmin:
    container_name: toledanonews-phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1